In [1]:
import numpy as np

### Lesson 1

In [2]:
A = np.array([1,2,3])

In [3]:
A+A

array([2, 4, 6])

In [4]:
A**2

array([1, 4, 9])

In [5]:
A**3

array([ 1,  8, 27])

In [6]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

### Lesson 2

In [7]:
a = np.array([1,2])
b = np.array([2,1])

In [8]:
dot = 0
for e,f in zip(a,b):
    dot += e*f
dot

4

In [9]:
np.sum(a*b)

4

In [10]:
(a*b).sum()

4

In [11]:
np.dot(a,b)

4

In [12]:
a.dot(b)

4

In [14]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.7999999999999998

In [15]:
angle = np.arccos(cosangle)
angle

0.6435011087932847

### Lesson 3

In [16]:
M = np.array([[1,2],[3,4]])
L = [[1,2],[3,4]]

In [17]:
L[0][0]

1

In [18]:
M[0,0]

1

In [20]:
# transpose
M.T

array([[1, 3],
       [2, 4]])

### Lesson 4

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# uniform distribution
np.random.random((5,5))

array([[0.20224134, 0.84020008, 0.95519163, 0.98035776, 0.04911197],
       [0.78360691, 0.23603924, 0.16066487, 0.53642541, 0.74864027],
       [0.45207552, 0.52536747, 0.3773944 , 0.01308175, 0.2516129 ],
       [0.96657017, 0.65884495, 0.08180094, 0.57376915, 0.38618422],
       [0.01782586, 0.48070202, 0.46614625, 0.87810804, 0.20413121]])

In [28]:
# guassian distribution
# mean = 0
# variance = 1
np.random.randn(5,5)

array([[ 1.4742261 ,  0.23661926,  0.45893391,  0.35838998, -0.06201445],
       [ 0.48375421,  0.07534814,  0.54282354,  0.78997389, -0.4431451 ],
       [-0.52224029,  0.18370751, -1.20699294,  0.35832358, -0.0129185 ],
       [ 0.42224314, -0.21412964,  2.65743403, -1.29226401,  1.15447645],
       [-0.53702861, -0.21347946, -0.41599206,  0.22670807,  0.9870255 ]])

In [29]:
np.random.randn(5,5).mean()

0.09327183423436568

In [30]:
np.random.randn(5,5).var()

1.0947967827010912

### Lesson 5

In [31]:
A = np.array([[1,2],[3,4]])

In [34]:
# inverse
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [35]:
# determinant
np.linalg.det(A)

-2.0000000000000004

In [36]:
np.diag(A)

array([1, 4])

In [41]:
np.diag(A).sum()

5

In [42]:
np.trace(A)

5

In [37]:
a = np.array([1,2])
b = np.array([3,4])

In [38]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [39]:
np.inner(a,b)

11

In [40]:
a.dot(b)

11

In [43]:
A = np.random.rand(100,3)

In [45]:
# transpose before calculating covariance
cov = np.cov(A.T)
cov

array([[ 0.08088971, -0.00709392,  0.00541913],
       [-0.00709392,  0.08704068, -0.00404538],
       [ 0.00541913, -0.00404538,  0.07987645]])

In [46]:
np.linalg.eig(cov)

(array([0.09451305, 0.07448194, 0.07881185]),
 array([[-0.54379376,  0.76969501,  0.3344517 ],
        [ 0.73527023,  0.24485234,  0.63200081],
        [-0.40455659, -0.58959047,  0.699083  ]]))

### Lesson 6

In [47]:
# solving linear system

In [50]:
A = np.array([[1,2],[3,4]])
b = np.array([1,2])

In [51]:
np.linalg.inv(A).dot(b)

array([2.22044605e-16, 5.00000000e-01])

In [53]:
# short version (preferred)
np.linalg.solve(A,b)

array([0. , 0.5])